{{- $root := . -}}
{{- range $key, $value := .Values.containers }}
{{- if $value.extraSecretEnvironmentVars }}
{{- if gt (len $value.extraSecretEnvironmentVars) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multi-stage-cron.fullname" $root }}-{{ $key }}
  labels:
    {{ include "multi-stage-cron.labels" $root | nindent 4 }}
type: Opaque
data:
  {{- range $secretKey, $secretValue := $value.extraSecretEnvironmentVars }}
  {{ $secretKey }} : {{ $secretValue | b64enc }}
  {{- end }}
{{- end }}  
{{- end }}
{{- end }}
